### ISSUE TITLE
Which orb-slam pipeline does this project referring to?

### ISSUE THREAD

**Issue by song-GAO-1992** [klammecr/superslam#1]
Hi, thanks for sharing so great work. I am curious about which orb-slam pipeline does this project referring to? Orb-slam2 or Orb-slam3?

**Comment by klammecr** [comment]
Hello! This is a modification of the ORB-SLAM2 pipeline. I will update the README to make this more clear. We are also transferring our code from another repo and plan to provide some additional details and code!

**Comment by song-GAO-1992** [comment]
> Hello! This is a modification of the ORB-SLAM2 pipeline. I will update the README to make this more clear. We are also transferring our code from another repo and plan to provide some additional details and code!

Thanks for reply. Looking forward to new developments of this project. :D
